### ISSUE TITLE
Request for Dataset

### ISSUE THREAD

**Issue by kqsykq** [GhostQ99/RobustTrainingGNN#1]
You and your team did a lot of excellent related work and gave me a lot of inspiration.  
I am wondering if you could kindly send me the dataset and the necessary information about it.  I promise to use it only for research . If it is not convenient, I hope that you will not be angry for my unreasonable request.
Thank you very much for your kind consideration and I am looking forward to your early reply.
All the best

**Comment by GhostQ99** [comment]
These are public datasets and you can find them in other works(e.g.  https://github.com/ChandlerBang/Pro-GNN, https://github.com/zhao-tong/GAug/tree/master/data/graphs). Hope it can help you.

**Comment by BonitoW** [comment]
Thanks so much for your excellent work.

I have the same concern about the dataset issue. Could you also provide the data split file? Thanks so much!

**Comment by GhostQ99** [comment]
As for the dataset setting, just keep it consistent with NRGNN(https://github.com/EnyanDai/NRGNN).
